vich_uploader:
    db_driver: orm

    mappings:
        courses:
            uri_prefix: /images/courses
            upload_destination: '%kernel.project_dir%/public/images/courses'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
